name: Reusable deployment step

on:
  workflow_call:
        
jobs:
  reusable-deployment-job:
    runs-on: windows-latest

    steps:
    
      - run: echo 'This is the secret' ${{ secrets.AZUREAPPSERVICE_CLIENTID_0431404336224C2AA26CEDDB755B239D }}
